    <div class="left">
      <span>[
        <a href="/ct/">ct</a> /
        <a href="/free/">free</a> /
        <a href="/nasa/">nasa</a> /
        <a href="/os/">os</a> /
        <a href="/prog/">prog</a>
      ]</span>

      <span>[
        <a href="/art/">art</a> /
        <a href="/int/">int</a> /
        <a href="/lewd/">lewd</a> /
        <a href="/misc/">misc</a> /
        <a href="/pol/">pol</a> /
        <a href="/vidya/">vidya</a> /
        <a href="/weeb/">weeb</a>
      ]</span>

      <span>[
        <a href="/meta/">meta</a> /
        <a href="/poll/">poll</a>
      ]</span>
    </div>

    <div class="right">
      [
        <a href="/">home</a> /
        <a href="/fqa">fqa</a> /
        <a href="/rules">rules</a> /
        <a href="/privacy">privacy</a> /
        <a href="/donate">donate</a> /
        <a href="/radio">radio</a> /
        <a href="/settings">settings</a> /
        <a href="http://kfarwell.org/projects/werchan/downloads/">sources</a>
      ]
    </div>
